name: publish

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Maven build + image build and publish
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          version-minor: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Package Jar. Re-package layered Jar. Build Image. Push to GHE.
        run: |
          mvn clean package -B -ntp jib:build
        env:
          IMAGE_TAG: latest
  job2:
    needs: job1
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment:
      name: 'Development'
      url: 'dev.jackbourner.co.uk'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          version-minor: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Development deployment'
        run: |
          mvn package jib:build 
          echo $KUBERNETES_PK | base64 --decode > private.key
          echo $KUBERNETES_CRT | base64 --decode > github.crt
          kubectl config set-cluster dev --server=https://jackbourner.co.uk:6443 --insecure-skip-tls-verify=true
          kubectl config set-credentials github-user --client-key=private.key --client-certificate=github.crt --embed-certs=true
          kubectl config set-context dev-context --cluster=dev --namespace=development --user=github-user
          kubectl config use-context dev-context 
          mvn k8s:resource k8s:apply
        env:
          env:
          KUBERNETES_CRT: ${{ secrets.KUBERNETES_CRT }}
          KUBERNETES_PK: ${{ secrets.KUBERNETES_PK }}
          IMAGE_TAG: 'dev'
          HOSTNAME: 'dev.jackbourner.co.uk'
  job3:
    needs: job2
    name: Deploy to Prod
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: 'jackbourner.co.uk'
    steps:
      - name: 'Production deployment'
        run: |
          Tag image with dev
          Login to kubenetes and set namespace to dev
          mvn k8s:resource k8s:apply
        env:
          IMAGE_TAG: prod
          HOSTNAME: 'jackbourner.co.uk'



# Build the image
# Update dev with the  latest image. Do I version the image and then update the deployment
# If success then trigger the prod build and get approval