name: publish

on: [push]

env:
  IMAGE_TAG: dev

jobs:
  build_and_publish_image:
    runs-on: ubuntu-latest
    name: Maven build + image build and publish
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          version-minor: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Package Jar. Re-package layered Jar. Build Image. Push to GHE.
        run: |
          mvn clean package -B -ntp jib:build 

