name: publish

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Maven build + image build and publish
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          version-minor: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Package Jar. Re-package layered Jar. Build Image. Push to GHE.
        run: |
          mvn clean package -B -ntp jib:build
        env:
          IMAGE_TAG: latest
  job2:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment:
      name: 'dev'
      url: 'dev.jackbourner.co.uk'
    steps:
      - name: 'Package Jar. Re-package layered Jar. Build Image. Push to GHE.'
        run: |
            ls -la
        env:
          IMAGE_TAG: dev
  job3:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: 'jackbourner.co.uk'
    steps:
      - name: 'Tag image and build deployment'
        run: |
          kubectl config view
        env:
          IMAGE_TAG: prod



# Build the image
# Update dev with the  latest image. Do I version the image and then update the deployment
# If success then trigger the prod build and get approval